# Generated by Django 4.0.6 on 2022-07-29 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('year', models.IntegerField(max_length=4)),
                ('device', models.TextField()),
                ('topplayer', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'games',
            },
        ),
    ]
